<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOdaxyvy\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOdaxyvy/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerOdaxyvy.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerOdaxyvy\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerOdaxyvy\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Odaxyvy',
    'container.build_id' => '6f5858ed',
    'container.build_time' => 1548795280,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerOdaxyvy');
