<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCs5opb7\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCs5opb7/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerCs5opb7.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerCs5opb7\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerCs5opb7\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Cs5opb7',
    'container.build_id' => 'f2560aad',
    'container.build_time' => 1548588200,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerCs5opb7');
