<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY5sxlki\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY5sxlki/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerY5sxlki.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerY5sxlki\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerY5sxlki\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Y5sxlki',
    'container.build_id' => '3878a1ec',
    'container.build_time' => 1548845098,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerY5sxlki');
